
# Site settings
title: TITLE
subtitle: SUBTITLE
email: your@email.com
description: JEKYLL SITE<br />Running on Git Hub pages
baseurl: "/saponidas.github.io" # the subpath of your site, e.g. /blog
url: "https://saponidas.github.io" # the base hostname & protocol for your site
author:
street_address: Calle Ejemplo
city: Ciudad
state: Provincia
zip_code: 55555
country: Spain
phone: +0034 111222333

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: href="https://facebook.com"
github_url:
gitlab_url: 
googleplus_url: href="https://facebook.com"
instagram_url: 
linkedin_url: href="https://facebook.com"
pinterest_url:
slack_url:
twitter_url: href="https://facebook.com"

# Build settings
markdown: kramdown
